backend:
  name: github
  repo: jancarlohendriks/jancarlohendriks.github.io

media_folder: "images/uploads"

collections:
  - name: "website-settings"
    label: "website settings"
    files:
      - label: "website settings"
        name: "site"
        file: "_data/site.yml"
        fields:
          - label: "Tel"
            name: "tel"
            widget: "string"